"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShortcutSchema = void 0;
const zod_1 = require("zod");
const supportedModifierKey = zod_1.z.enum(['Alt', 'Control', 'Meta', 'Super', 'CommandOrCtrl']);
const supportedShortcutKey = zod_1.z.enum([
    'Comma',
    'Period',
    'Forwardslash',
    'Slash',
    'Tab',
    'Space',
    'Enter',
    'Escape',
    'ArrowUp',
    'ArrowDown',
    'ArrowLeft',
    'ArrowRight',
    'F1',
    'F2',
    'F3',
    'F4',
    'F5',
    'F6',
    'F7',
    'F8',
    'F9',
    'F10',
    'F11',
    'Digit9',
    'Digit8',
    'Digit7',
    'Digit6',
    'Digit5',
    'Digit4',
    'Digit3',
    'Digit2',
    'Digit1',
    'Digit0',
    'KeyA',
    'KeyB',
    'KeyC',
    'KeyD',
    'KeyE',
    'KeyF',
    'KeyG',
    'KeyH',
    'KeyI',
    'KeyJ',
    'KeyK',
    'KeyL',
    'KeyM',
    'KeyN',
    'KeyO',
    'KeyP',
    'KeyQ',
    'KeyR',
    'KeyS',
    'KeyT',
    'KeyU',
    'KeyV',
    'KeyW',
    'KeyX',
    'KeyY',
    'KeyZ',
    'NumpadDivide',
    'NumpadMultiply',
    'NumpadSubtract',
    'NumpadAdd',
    'NumpadDecimal',
    'Numpad9',
    'Numpad8',
    'Numpad7',
    'Numpad6',
    'Numpad5',
    'Numpad4',
    'Numpad3',
    'Numpad2',
    'Numpad1',
    'Numpad0'
]);
exports.ShortcutSchema = zod_1.z.object({
    modifierKeys: zod_1.z.array(supportedModifierKey).default([]),
    shortcutKey: supportedShortcutKey,
    enabled: zod_1.z.boolean().default(true),
    configuring: zod_1.z.boolean().default(false)
});
